// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/v1/fastpath.proto

package fastpathv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	PoolRef       string                 `protobuf:"bytes,2,opt,name=pool_ref,json=poolRef,proto3" json:"pool_ref,omitempty"`
	ExposedPorts  []int32                `protobuf:"varint,3,rep,packed,name=exposed_ports,json=exposedPorts,proto3" json:"exposed_ports,omitempty"`
	Command       []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateRequest) GetPoolRef() string {
	if x != nil {
		return x.PoolRef
	}
	return ""
}

func (x *CreateRequest) GetExposedPorts() []int32 {
	if x != nil {
		return x.ExposedPorts
	}
	return nil
}

func (x *CreateRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CreateRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	AgentPod      string                 `protobuf:"bytes,2,opt,name=agent_pod,json=agentPod,proto3" json:"agent_pod,omitempty"`
	Endpoints     []string               `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"` // IP:Port 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateResponse) GetAgentPod() string {
	if x != nil {
		return x.AgentPod
	}
	return ""
}

func (x *CreateResponse) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_fastpath_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_fastpath_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_v1_fastpath_proto protoreflect.FileDescriptor

const file_api_proto_v1_fastpath_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/fastpath.proto\x12\vfastpath.v1\"\x93\x01\n" +
	"\rCreateRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x19\n" +
	"\bpool_ref\x18\x02 \x01(\tR\apoolRef\x12#\n" +
	"\rexposed_ports\x18\x03 \x03(\x05R\fexposedPorts\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\"j\n" +
	"\x0eCreateResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1b\n" +
	"\tagent_pod\x18\x02 \x01(\tR\bagentPod\x12\x1c\n" +
	"\tendpoints\x18\x03 \x03(\tR\tendpoints\".\n" +
	"\rDeleteRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa5\x01\n" +
	"\x0fFastPathService\x12H\n" +
	"\rCreateSandbox\x12\x1a.fastpath.v1.CreateRequest\x1a\x1b.fastpath.v1.CreateResponse\x12H\n" +
	"\rDeleteSandbox\x12\x1a.fastpath.v1.DeleteRequest\x1a\x1b.fastpath.v1.DeleteResponseB Z\x1efast-sandbox/api/v1;fastpathv1b\x06proto3"

var (
	file_api_proto_v1_fastpath_proto_rawDescOnce sync.Once
	file_api_proto_v1_fastpath_proto_rawDescData []byte
)

func file_api_proto_v1_fastpath_proto_rawDescGZIP() []byte {
	file_api_proto_v1_fastpath_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_fastpath_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_fastpath_proto_rawDesc), len(file_api_proto_v1_fastpath_proto_rawDesc)))
	})
	return file_api_proto_v1_fastpath_proto_rawDescData
}

var file_api_proto_v1_fastpath_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_fastpath_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: fastpath.v1.CreateRequest
	(*CreateResponse)(nil), // 1: fastpath.v1.CreateResponse
	(*DeleteRequest)(nil),  // 2: fastpath.v1.DeleteRequest
	(*DeleteResponse)(nil), // 3: fastpath.v1.DeleteResponse
}
var file_api_proto_v1_fastpath_proto_depIdxs = []int32{
	0, // 0: fastpath.v1.FastPathService.CreateSandbox:input_type -> fastpath.v1.CreateRequest
	2, // 1: fastpath.v1.FastPathService.DeleteSandbox:input_type -> fastpath.v1.DeleteRequest
	1, // 2: fastpath.v1.FastPathService.CreateSandbox:output_type -> fastpath.v1.CreateResponse
	3, // 3: fastpath.v1.FastPathService.DeleteSandbox:output_type -> fastpath.v1.DeleteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_fastpath_proto_init() }
func file_api_proto_v1_fastpath_proto_init() {
	if File_api_proto_v1_fastpath_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_fastpath_proto_rawDesc), len(file_api_proto_v1_fastpath_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_fastpath_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_fastpath_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_fastpath_proto_msgTypes,
	}.Build()
	File_api_proto_v1_fastpath_proto = out.File
	file_api_proto_v1_fastpath_proto_goTypes = nil
	file_api_proto_v1_fastpath_proto_depIdxs = nil
}
