// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: api/proto/v1/fastpath.proto

package fastpathv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FastPathService_CreateSandbox_FullMethodName = "/fastpath.v1.FastPathService/CreateSandbox"
	FastPathService_DeleteSandbox_FullMethodName = "/fastpath.v1.FastPathService/DeleteSandbox"
)

// FastPathServiceClient is the client API for FastPathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FastPathServiceClient interface {
	// CreateSandbox 极速创建沙箱，绕过 K8s 控制面延迟
	CreateSandbox(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// DeleteSandbox 极速删除沙箱
	DeleteSandbox(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type fastPathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFastPathServiceClient(cc grpc.ClientConnInterface) FastPathServiceClient {
	return &fastPathServiceClient{cc}
}

func (c *fastPathServiceClient) CreateSandbox(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, FastPathService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) DeleteSandbox(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, FastPathService_DeleteSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FastPathServiceServer is the server API for FastPathService service.
// All implementations must embed UnimplementedFastPathServiceServer
// for forward compatibility.
type FastPathServiceServer interface {
	// CreateSandbox 极速创建沙箱，绕过 K8s 控制面延迟
	CreateSandbox(context.Context, *CreateRequest) (*CreateResponse, error)
	// DeleteSandbox 极速删除沙箱
	DeleteSandbox(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedFastPathServiceServer()
}

// UnimplementedFastPathServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFastPathServiceServer struct{}

func (UnimplementedFastPathServiceServer) CreateSandbox(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) DeleteSandbox(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) mustEmbedUnimplementedFastPathServiceServer() {}
func (UnimplementedFastPathServiceServer) testEmbeddedByValue()                         {}

// UnsafeFastPathServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FastPathServiceServer will
// result in compilation errors.
type UnsafeFastPathServiceServer interface {
	mustEmbedUnimplementedFastPathServiceServer()
}

func RegisterFastPathServiceServer(s grpc.ServiceRegistrar, srv FastPathServiceServer) {
	// If the following call panics, it indicates UnimplementedFastPathServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FastPathService_ServiceDesc, srv)
}

func _FastPathService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).CreateSandbox(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).DeleteSandbox(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FastPathService_ServiceDesc is the grpc.ServiceDesc for FastPathService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FastPathService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastpath.v1.FastPathService",
	HandlerType: (*FastPathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _FastPathService_CreateSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _FastPathService_DeleteSandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/fastpath.proto",
}
