apiVersion: sandbox.fast.io/v1alpha1
kind: SandboxPool
metadata:
  name: test-sandbox-pool
  namespace: default
spec:
  agentTemplate:
    metadata:
      labels:
        app: sandbox-agent
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fast-sandbox/agent:dev
        imagePullPolicy: IfNotPresent
        name: agent
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 2345
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
      serviceAccountName: default
  capacity:
    bufferMax: 1
    bufferMin: 1
    poolMax: 1
    poolMin: 1